# Перечень volume
volumes:
  pg_data:

  static:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Имя и описание контейнера с бэкендом
  backend:
    env_file: .env
    # Из какого Dockerfile собирать образ для этого контейнера:
    build: ./backend/
    # Тут подключаем volume к backend
    volumes:
      - static:/backend_static
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db

  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

  gateway:
    env_file: .env
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    build: ./gateway/
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера

    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
